print('Как Вас зовут?')
name = input('Меня зовут ')
print('Привет', name)
print('Ваша фамилия?')
surname = input('Моя фамилия ')
print('Приятно познакомиться,', name, surname, '!')
print('Сколько Вам лет?')
age = int(input('Мне '))
print(age, 'лет, прекрасный возраст!')
print('Сколько лет Вы работаете?')
age2 = int(input())
print(age2, ', отличный стаж работы!')
